### ISSUE TITLE
Specific custom songs cause loading issues

### ISSUE THREAD

**Issue by ChaosInTheSnow** [kihecido/BMBF#12]
I noticed an issue with my song library in after updating BMBF. Initially when I selected to reload the library, it created a bunch of song entries in the custom songs section of the playlists tab in BMBF, all with the custom songs icon and no meta data. Then in the game, I saw the custom songs playlist but there are no songs listed.

I then tried deleting all the entries in the custom songs dir and copied a single song in, this worked.

After testing some more, certain songs that used to work now seem to cause issues with reloading the library.

Two such songs are:
38ad (Silence ft. Khalid (Slushii Remix) - BluuYT)
731-481 Senbonzakura - Kurousa P - f.Hatsune Miku

I had about 200 songs in the library I was copying and out of the first 70 these two were the only ones with issues.

To correct the issues when I run into it I have been doing the following:
- Delete the offending song (once I find it) from the custom songs dir
- Reload the library
- Re-sync Beat Saber
- Try and copy the next batch of songs

Each time one of these songs causes an issue, the following things happen:
- The popup that comes up when reloading the library no longer goes through the full list of songs and instead disappears quickly
- There will be several new entries at the bottom of the custom song list in the playlists section of BMBF, that have their icons duplicated from existing songs, but do not have the meta data on the title, author etc. 

Unfortunately I have no idea what is the actual issue with these songs (which makes finding them a tedious process of a sort of manual binary search). I also have no idea whether this is just something on my side.

Anyway, I will continue on with copying them in batches but thought I would pass this on since it's a bit odd.

Thanks for all the hard work on getting the update out quickly.

**Comment by Arakon** [comment]
According to a comment in the BSMG discord, periods in the song name are causing problems currently. Try renaming the song without a period in the title (i.e. the "ft." to "ft").

**Comment by ChaosInTheSnow** [comment]
Thanks so much for the info! I actually thought periods were used fairly often in the dir names, but looking over my library there were only about 7 songs that had them. I renamed them and now the whole library is loaded correctly.

**Comment by ChaosInTheSnow** [comment]
Sorry, close that on the basis that the fix worked, but will leave open since it is an ongoing issue and should be fixed in the underlying code

**Comment by jackcbel** [comment]
None of my songs is loading 4 now , they list up and start to play but on the right hand side the circle keeps turning and no more info shows, no way to select the dificulty

**Comment by ChaosInTheSnow** [comment]
I had that issue initially when I tried to re-install the latest version of Beat Saber and patched it with the 1.4.5 code. But since the 1.5.0 release things have been working for me aside from a few edge cases.

Because I was trying to debug the issue listed here, what I did was probably overkill, but the following is the cleanest way I know of if all else fails:
1) Load SideQuest, go to My Apps and uninstall Beat Saber and the two BMBF apk files (weloveoculus.BMBF and weloveoculus.wrapper)
2) Make a backup of your existing BMBFData dir on the Quest and the BMBFservice file (which is in the main Quest dir)
3) Delete both of the above (again, after backing them up)
4) On the Quest re-install Beat Saber. If Beta Saber is still listed as installed even though you uninstalled in step 1 via SideQuest, click play and it should tell you there's an update available. It will then install normally
5) Run Beat Saber once an quit
6) Download BMBF_TVWrapper.apk and com.weloveoculus.BMBF.apk from the 1.5.0 release
7) Click the install APK from file icon at the top right in SideQuest and install the two APKs
8) On the Quest go to library-> unknown sources and select the BMBF APK
9) Go through that install process as instructed
10) On the Quest select the three dots beside the Beat Saber icon in the library and make sure it has storage permissions
11) On your PC go to the Quest volume and there should be a new BMBFData dir. If there is then make a CustomSongs dir and copy one song from your backed up CustomSongs dir from earlier. 
If that the BMBF dir is not there you can try restarting the Quest to make it show up
12) On the Quest load BMBF via unknown sources, go to tools and update the song library. It should pick up the song you just copied (which should now be present in the right hand side of the playlist tab in BMBF)
13) Click the sync button and make sure the popup shows up that says it's updating the config file. I sometimes have to press the sync button many times before this happens. Once it has successfully done it will no longer say sync and instead say start Beat Saber
14) Go into Beat Saber on the Quest and verify that your song is now in the custom maps and that the play icon appears
15) If that works copy the rest of the library into the CustomSongs dir and repeat steps 12 and 13

As I say, the above is overkill and probably has some steps that are not actually needed but from a sanity check perspective I think it is sort of guaranteed to avoid issues. I will say that I have a few songs in my library that are still not loading (still have the spinning circle issue). But it's only 4 out of about 200 so I'm not that bothered about it. But if your test with the first song doesn't work, then try repeating with another couple of songs just in case. And as discussed in this comments thread, make sure none of the directory names have a period in them

**Comment by micfogas** [comment]
This behavior is also consistent with maps when they require Mapping Extensions, but the mod is not installed. So if you're getting it with a few songs still, it's likely that those maps depend on that mod.




On Sun, Dec 15, 2019 at 4:40 AM -0800, "ChaosInTheSnow" <notifications@github.com> wrote:












I had that issue initially when I tried to re-install the latest version of Beat Saber and patched it with the 1.4.5 code. But since the 1.5.0 release things have been working for me aside from a few edge cases.


Because I was trying to debug the issue listed here, what I did was probably overkill, but the following is the cleanest way I know of if all else fails:

Load SideQuest, go to My Apps and uninstall Beat Saber and the two BMBF apk files (weloveoculus.BMBF and weloveoculus.wrapper)
Make a backup of your existing BMBFData dir on the Quest and the BMBFservice file (which is in the main Quest dir)
Delete both of the above (again, after backing them up)
On the Quest re-install Beat Saber. If Beta Saber is still listed as installed even though you uninstalled in step 1 via SideQuest, click play and it should tell you there's an update available. It will then install normally
Run Beat Saber once an quit
Download BMBF_TVWrapper.apk and com.weloveoculus.BMBF.apk from the 1.5.0 release
Click the install APK from file icon at the top right in SideQuest and install the two APKs
On the Quest go to library-> unknown sources and select the BMBF APK
Go through that install process as instructed
On the Quest select the three dots beside the Beat Saber icon in the library and make sure it has storage permissions
On your PC go to the Quest volume and there should be a new BMBFData dir. If there is then make a CustomSongs dir and copy one song from your backed up CustomSongs dir from earlier.

If that the BMBF dir is not there you can try restarting the Quest to make it show up
On the Quest load BMBF via unknown sources, go to tools and update the song library. It should pick up the song you just copied (which should now be present in the right hand side of the playlist tab in BMBF)
Click the sync button and make sure the popup shows up that says it's updating the config file. I sometimes have to press the sync button many times before this happens. Once it has successfully done it will no longer say sync and instead say start Beat Saber
Go into Beat Saber on the Quest and verify that your song is now in the custom maps and that the play icon appears
If that works copy the rest of the library into the CustomSongs dir and repeat steps 12 and 13



As I say, the above is overkill and probably has some steps that are not actually needed but from a sanity check perspective I think it is sort of guaranteed to avoid issues. I will say that I have a few songs in my library that are still not loading (still have the spinning circle issue). But it's only 4 out of about 200 so I'm not that bothered about it. But if your test with the first song doesn't work, then try repeating with another couple of songs just in case. And as discussed in this comments thread, make sure none of the directory names have a period in them

**Comment by jackcbel** [comment]
Thx it totally worked !!!



Verstuurd vanaf mijn iPhone
