### ISSUE TITLE
BMBF 1.5 for Beatsaber 1.6 (Infinite Loading)

### ISSUE THREAD

**Issue by ShootMePlz** [kihecido/BMBF#34]
After following countless tutorials and starting from scratch multiple times the same problem persists. I download the modded beat saber through following the BMBF's request and try to bootup beat saber. Every time I am greeted with three dots and beat saber never loads. I have enabled permissions for beat saber and rebooted my quest multiple times. I have the latest APK versions and have tried the quick fix tools in BMBF itself. If anyone has a similar problem or knows where I went wrong please be sure to reach out and help a fellow out <3.

**Comment by JonnyXDA** [comment]
Check the mods you have active.  If in doubt, disable them all - some mods have not yet been updated for 1.6.3.

**Comment by ShootMePlz** [comment]
I just got my quest so I haven't modded or sideloaded anything but this BMBF.

**Comment by ShootMePlz** [comment]
Also thank you for responding!

**Comment by JonnyXDA** [comment]
Try uninstalling, then reinstalling and re-patching with BMBF again

**Comment by rlh6f** [comment]
I am having this exact same experience as well.  I tried installing BMBF with both SideQuest and QuestSongsInstaller.   I didn't try installing for the first time until the day after version 1.7 of BeatSaber was released, so I thought my problems were related to that, and was hoping it would be resolved in next BMBF update, but it appears that other people are mostly successfully using BMBF 1.5.0.0 with the latest update.  I'm out of ideas for troubleshooting.  Any suggestions?

**Comment by rlh6f** [comment]
I just wanted to follow-up.  I tried again today, and before uninstalling BeatSaber through SideQuest, I did a 'clear app data' first.  This time, when I started BeatSaber after a fresh install it asked if I wanted the tutorial since it looked like my first time playing.  And then I was able to get it to work, following the steps here: https://github.com/the-expanse/SideQuest/wiki/BMBF
So, things *can* still currently work for a new/fresh install, just make sure to really clean up and reboot before trying again.  It took me several failed attempts before I finally got it working.
