### ISSUE TITLE
Is the recent update of beat saber supports this updated BMBF?

### ISSUE THREAD

**Issue by slazzher206** [kihecido/BMBF#37]

**Comment by OnAQuest** [comment]
Yes. I believe so. However, you must find updated mods (1.6.3 currently) and apply them. If you apply old mods onto a newer version of Beat Saber, it will infinitely load or the mod won't work.

**Comment by micfogas** [comment]
I believe sabers and trails work, at least they did for 1.6.0. I've used redrumblers sabers and fire trail, and also the SSEv3 saber with success. sadly, mods like scoresaber and hit colorizer haven't been and most likely will never be updated. Id have to check if map extensions have been updated but they most likely have. check the BSMG discord channel for info about updates





On Wed, Jan 22, 2020 at 3:35 PM -0800, "OnAQuest" <notifications@github.com> wrote:












Yes. I believe so. However, you must find updated mods (1.6.3 currently) and apply them. If you apply old mods onto a newer version of Beat Saber, it will infinitely load or the mod won't work.

**Comment by exqcme** [comment]
Anyone know if new newest update with the camellia  song work? i havent upate since 360 got released and realise there no new bmbf for a wwhile now?
thank you!

**Comment by saltyfries47** [comment]
I’ve tried using it but the new camellia songs disappear.

**Comment by micfogas** [comment]
then you need to start over. uninstall, then reinstall beat saber from the store. open the game like usual, then do bmbf, after installing the modded beat saber back on thru bmbf, don't choose to reload your previous playlists. don't install any mods this time. then you should be able to install songs from there. I'm not sure if reloading the custom songs folder will remove access to the new songs. doesn't seem like it should since it's just scanning the custom songs folder to add detected songs to the custom songs playlist. 




bmbf 1.5 was written for beatsaber 1.6 so it doesn't have built in support for the new song pack natively. if you have issues with that, you're gonna have to wait for an updated version of bmbf that is made for 1.7 ... keep in mind that this is a side project for the unicorns and I suspect further beatsaber updates will try to make it increasingly difficult for bmbf as Facebook tries to combat piracy/copyright infringement. if you really want the new songs to stay, the safest way I know of is to do a fresh beatsaber/bmbf install and then reinstall your songs from either downloaded .zip files for each song, thru bmbf one-click install off beatsaber/beastsaber, or using syncsaber bookmarks to auto reinstall your bookmarked songs.




if the first option above fails to work (reloading custom songs folder), then this is the only other solution right now that's automated that will keep the new songs for you




On Sun, Feb 2, 2020 at 10:46 AM -0800, "saltyfries47" <notifications@github.com> wrote:












I’ve tried using it but the new camellia songs disappear.
